/**
 * TourConfig — Role-specific spotlight tour steps for Nexify
 * Each step: { id, route, selector, title, subtitle, body, hint, position, icon }
 *
 * route    — the actual page path to navigate to (null = same page as previous)
 * selector — CSS [data-tour="..."] attribute of the element to spotlight
 * position — tooltip anchor: 'top' | 'bottom' | 'left' | 'right'
 * icon     — lucide icon name string (used as JSX tag)
 */

export const TOUR_STEPS = {
  STUDENT: [
    {
      id: 'student-welcome',
      route: '/student',
      selector: '[data-tour="student-stats-grid"]',
      title: 'Your Learning Dashboard',
      subtitle: 'Overview',
      body: 'This is your command center. The top row shows your enrolled courses, total spent, average progress across all courses, and your current learning streak. These stats update automatically as you watch lessons and complete courses.',
      hint: 'Your stats card shows real-time data — check back after each lesson!',
      position: 'bottom',
      icon: 'BarChart3',
    },
    {
      id: 'student-courses',
      route: '/student',
      selector: '[data-tour="student-stats-grid"]',
      title: 'My Courses — Your Active Learning',
      subtitle: 'My Learning',
      body: 'All your enrolled courses are listed in the My Learning section. You can see your progress bar, completed lessons, and the next lesson to watch. Click any course card to jump straight into the lesson player. When you finish all lessons, a certificate becomes available.',
      hint: 'Click the "Continue Learning" button to pick up right where you left off.',
      position: 'right',
      icon: 'BookOpen',
    },
    {
      id: 'student-player',
      route: '/student/profile',
      selector: '[data-tour="student-profile-stats"]',
      title: 'Course Player — Lesson by Lesson',
      subtitle: 'Course Player',
      body: 'When you open any enrolled course, you\'ll see the full video lesson player. The progress bar shows how many lessons you\'ve completed. Use the sidebar to jump between modules and lessons. Your progress is saved automatically as you mark lessons complete.',
      hint: 'Find any enrolled course in your Profile page and click it to start watching!',
      position: 'top',
      icon: 'Play',
    },
    {
      id: 'student-earnings',
      route: '/student/profile',
      selector: '[data-tour="student-profile-stats"]',
      title: 'Referral Rewards — Earn While You Learn',
      subtitle: 'Rewards',
      body: 'Share your unique referral link with friends. When they enroll in a course, you earn a commission credited to your balance. Check your referral link and earnings stats in your Profile page. Request a payout once you reach the minimum threshold.',
      hint: 'Your referral link is on your Profile page — share it on WhatsApp to start earning!',
      position: 'right',
      icon: 'DollarSign',
    },
    {
      id: 'student-profile',
      route: '/student/profile',
      selector: '[data-tour="student-profile-stats"]',
      title: 'Profile & Settings — Your Learning Identity',
      subtitle: 'Account',
      body: 'Your profile shows your total enrolled courses, in-progress count, reviews written, and certificates earned. Switch between the My Courses, Reviews, and Certificates tabs to see detailed records. Update your account settings at the top right.',
      hint: 'Write a review after completing a course — it helps other students choose!',
      position: 'bottom',
      icon: 'User',
    },
    {
      id: 'student-nexa',
      route: '/student',
      selector: '[data-tour="nexa-widget-fab"]',
      title: 'Nexa AI — Your Personal Learning Assistant',
      subtitle: 'AI Assistant',
      body: 'The purple brain button is Nexa, your AI tutor. Click it anytime to ask questions about your course content, get lesson summaries, or find recommended next steps. Nexa knows your enrolled courses and progress — ask anything specific.',
      hint: 'Try: "What lesson should I watch next in my Python course?"',
      position: 'left',
      icon: 'Brain',
    },
  ],

  CREATOR: [
    {
      id: 'creator-dashboard',
      route: '/creator',
      selector: '[data-tour="creator-stats-row"]',
      title: 'Creator Studio — Your Business Dashboard',
      subtitle: 'Overview',
      body: 'This is your creator command center. The top row shows your total revenue in GH₵, number of published courses, total students enrolled, and pending payouts. These numbers update in real time as students enroll.',
      hint: 'Your GH₵ revenue is paid out on the 1st and 15th of each month!',
      position: 'bottom',
      icon: 'LayoutDashboard',
    },
    {
      id: 'creator-new-course',
      route: '/creator',
      selector: '[data-tour="creator-course-builder-cta"]',
      title: 'Course Builder — Build Your First Course',
      subtitle: 'Course Builder',
      body: 'Click "Create New Course" on your dashboard to start building. Fill in your course title, description, and select a category. Add a cover image, set your price in GH₵, choose the type (Digital or In-Person Lab), and set a skill level. Save draft or submit for review when ready.',
      hint: 'Add a 30–90 second trailer video — courses with trailers convert 3x better!',
      position: 'right',
      icon: 'Plus',
    },
    {
      id: 'creator-courses',
      route: '/creator',
      selector: '[data-tour="creator-course-list"]',
      title: 'My Courses — Manage Everything',
      subtitle: 'Course Management',
      body: 'Every course you\'ve created appears here with its status: PUBLISHED (live to students), PENDING (awaiting admin review), or DRAFT. Click Edit to modify content, click Stats for detailed analytics, or click Submit to send a draft for approval.',
      hint: 'Edit your course anytime, even after publishing — changes go live immediately.',
      position: 'right',
      icon: 'BookOpen',
    },
    {
      id: 'creator-assets',
      route: '/creator',
      selector: '[data-tour="creator-assets-upload"]',
      title: 'Asset Manager — Upload Your Media',
      subtitle: 'Media Library',
      body: 'The Promo Asset Manager lets you upload course videos, images, PDFs, and downloadable resources. All your media files are organized and ready to attach to lessons. Supported formats: MP4, MOV, PDF, JPG, PNG. Uploads are processed and stored securely on the platform.',
      hint: 'Upload your course trailer here first, then attach it in the Course Builder!',
      position: 'top',
      icon: 'FolderOpen',
    },
    {
      id: 'creator-analytics',
      route: '/creator',
      selector: '[data-tour="creator-stats-row"]',
      title: 'Analytics — Track Your Performance',
      subtitle: 'Analytics',
      body: 'Deep dive into your course performance on your dashboard. See enrollments, student counts, and revenue across all your courses. Check your published courses list to understand which content converts best.',
      hint: 'Check which courses have the most students — that tells you what content works!',
      position: 'left',
      icon: 'TrendingUp',
    },
    {
      id: 'creator-earnings',
      route: '/creator/earnings',
      selector: '[data-tour="creator-earnings-summary"]',
      title: 'Earnings & Payouts — Your Revenue',
      subtitle: 'Payouts',
      body: 'This page shows your total revenue, platform fee deduction, and net earnings. View the per-course breakdown showing which courses are generating the most revenue. Set your bank details to receive payouts on the 1st and 15th.',
      hint: 'Set your bank details in Payout Settings to receive your first payout!',
      position: 'bottom',
      icon: 'DollarSign',
    },
    {
      id: 'creator-staging',
      route: '/creator',
      selector: '[data-tour="creator-course-builder-cta"]',
      title: 'Staging Queue — Submit Your Course for Review',
      subtitle: 'Staging',
      body: 'After you submit a course for review, it goes to our admin team for approval. Most courses are reviewed within 24 hours. Track your submission status directly from this dashboard — approved courses go live immediately on the marketplace. Check the staging queue link in your admin panel to see pending reviews.',
      hint: 'Most courses are approved within 24 hours of submission!',
      position: 'right',
      icon: 'ClipboardList',
    },
    {
      id: 'creator-profile',
      route: '/creator/profile',
      selector: '[data-tour="creator-profile-stats"]',
      title: 'Profile & Settings — Your Creator Identity',
      subtitle: 'Settings',
      body: 'Your creator profile shows published course count, pending count, total students, and lifetime revenue. Use the tabs to switch between My Courses, Revenue breakdown, Payout Settings, and Instructor Profile (your public bio shown on course pages).',
      hint: 'Fill in your Instructor Profile — students are 2x more likely to enroll from a complete profile!',
      position: 'bottom',
      icon: 'Settings',
    },
  ],

  AFFILIATE: [
    {
      id: 'affiliate-dashboard',
      route: '/affiliate',
      selector: '[data-tour="affiliate-stats-row"]',
      title: 'Affiliate Hub — Your Partner Dashboard',
      subtitle: 'Overview',
      body: 'This is your affiliate command center. The four stat cards show your total clicks (how many times people clicked your links), conversions (actual enrollments), pending balance (awaiting payout), and cleared balance (ready to withdraw). The live sales chart updates as people click your links.',
      hint: 'Share your link consistently — 5+ shares per week correlates with first sale within 7 days!',
      position: 'bottom',
      icon: 'LayoutDashboard',
    },
    {
      id: 'affiliate-tools',
      route: '/affiliate',
      selector: '[data-tour="affiliate-tools-vault"]',
      title: 'Promoter Tools — Ready-Made Scripts',
      subtitle: 'Promo Tools',
      body: 'The Promoter Asset Vault gives you copy-paste WhatsApp scripts, TikTok video hooks, email templates, and banner images created by the course creators. Browse the tabs to find the right format for your audience — no creative work needed, just copy and share.',
      hint: 'The WhatsApp script works great for group broadcasts — paste it directly!',
      position: 'right',
      icon: 'Wand2',
    },
    {
      id: 'affiliate-links',
      route: '/affiliate/links',
      selector: '[data-tour="affiliate-link-generator"]',
      title: 'Link Generator — Create Tracking Links',
      subtitle: 'Tracking Links',
      body: 'Select any course from the dropdown and generate a unique affiliate tracking link. Your link is automatically tied to your account — every click and sale is tracked. Copy the link and share it anywhere. The table below shows all your existing links with live click and sale counts.',
      hint: 'Link to the specific course page, not the homepage — conversion is 4x higher!',
      position: 'right',
      icon: 'Link2',
    },
    {
      id: 'affiliate-earnings',
      route: '/affiliate',
      selector: '[data-tour="affiliate-stats-row"]',
      title: 'Earnings — Your Commission History',
      subtitle: 'Commissions',
      body: 'Check your affiliate dashboard for commission history. Your total earned, pending balance, and cleared balance are all shown in the stat cards at the top. Earnings are marked Pending until the student\'s payment is confirmed, then moved to Cleared for payout.',
      hint: 'Commission rates vary by course — promote courses with the highest commissions first!',
      position: 'left',
      icon: 'DollarSign',
    },
    {
      id: 'affiliate-leaderboard',
      route: '/affiliate',
      selector: '[data-tour="affiliate-onboarding-tracker"]',
      title: 'Leaderboard & Progress Tracker',
      subtitle: 'Rankings',
      body: 'The leaderboard shows the top affiliates ranked by total earnings. Your current rank and all-time stats are shown. The onboarding tracker shows your progress from creating an account to making your first sale. Climb the ranks by promoting consistently.',
      hint: 'Top 3 affiliates earn bonus commissions — aim for the podium!',
      position: 'top',
      icon: 'Trophy',
    },
    {
      id: 'affiliate-profile',
      route: '/affiliate/profile',
      selector: '[data-tour="affiliate-profile-stats"]',
      title: 'Profile & Payout Settings',
      subtitle: 'Account',
      body: 'Your profile shows your total earned, pending payout, total clicks, and conversion rate. Use the tabs to manage your Referral Links, Payout History, and Payment Details. Set up Mobile Money or bank transfer to receive your commissions.',
      hint: 'Add your Mobile Money number in Payment Details — payouts process within 48 hours!',
      position: 'bottom',
      icon: 'User',
    },
  ],

  ADMIN: [
    {
      id: 'admin-dashboard',
      route: '/admin',
      selector: '[data-tour="admin-gmv-chart"]',
      title: 'Admin Dashboard — Platform Command Center',
      subtitle: 'Overview',
      body: 'This is the Nexify control room. The GMV chart shows total platform Gross Merchandise Value over time. Below it are platform health indicators, active user counts, and pending course reviews. The AI Insights card gives you automated recommendations based on platform data.',
      hint: 'Check the GMV chart weekly — a downward trend in any category needs attention!',
      position: 'top',
      icon: 'Shield',
    },
    {
      id: 'admin-users',
      route: '/admin/users',
      selector: '[data-tour="admin-user-grid"]',
      title: 'User Management — All Platform Users',
      subtitle: 'Users',
      body: 'Every user on Nexify — students, creators, affiliates, and admins — is listed here. Filter by role to see specific groups. Click any user to update their role, suspend their account, or verify their identity. Use pagination to navigate large user lists.',
      hint: 'Verify creators to give them a Trust Badge — it increases their course conversion rate!',
      position: 'right',
      icon: 'Users',
    },
    {
      id: 'admin-staging',
      route: '/admin/staging',
      selector: '[data-tour="admin-staging-queue"]',
      title: 'Staging Queue — Course Approvals',
      subtitle: 'Course Review',
      body: 'Creator courses awaiting your review appear here. Each card shows the course title, creator, type, price, and number of modules. Click Approve to publish immediately, or Reject with an optional reason. Most courses should be reviewed within 24 hours of submission.',
      hint: 'Approve courses with complete modules, a trailer, and fair pricing — reject ones with placeholder content.',
      position: 'right',
      icon: 'ClipboardCheck',
    },
    {
      id: 'admin-metrics',
      route: '/admin/metrics',
      selector: '[data-tour="admin-platform-metrics"]',
      title: 'Platform Analytics — Full Metrics View',
      subtitle: 'Analytics',
      body: 'Comprehensive platform metrics: total GMV, platform fees collected, active users by role, course count by status, and conversion funnel data. Use these numbers to make decisions about platform fees, featured sections, and creator incentives.',
      hint: 'Compare this week vs last week to spot trends before they become problems!',
      position: 'left',
      icon: 'BarChart3',
    },
    {
      id: 'admin-nexa',
      route: '/admin/nexa-settings',
      selector: '[data-tour="admin-nexa-settings-panel"]',
      title: 'Nexa AI Configuration',
      subtitle: 'AI Settings',
      body: 'Configure Nexa\'s behavior across the platform. Set the AI\'s name, avatar, system prompt (the instructions that define its personality), default responses for common questions, and which features are enabled per role. Changes apply immediately to all users.',
      hint: 'A warm, helpful system prompt increases student engagement with Nexa by ~30%!',
      position: 'right',
      icon: 'Cpu',
    },
    {
      id: 'admin-assets',
      route: '/admin/assets',
      selector: '[data-tour="admin-asset-manager"]',
      title: 'Asset Manager — Platform Branding',
      subtitle: 'Branding',
      body: 'Manage the platform\'s visual assets: main logo, light logo variant, Nexa avatar, course placeholder image, and payment method badges (MoMo MTN, Telecel, AT). Upload new versions to update branding across the entire platform instantly.',
      hint: 'Update the course placeholder to a branded image that matches your platform\'s style!',
      position: 'top',
      icon: 'Image',
    },
    {
      id: 'admin-ads',
      route: '/admin/ad-manager',
      selector: '[data-tour="admin-ad-manager-list"]',
      title: 'Ad Manager — Platform Advertisements',
      subtitle: 'Ads',
      body: 'Create and manage banner ads shown across the platform — on the landing page hero, course cards, sidebar, and footer. Set the ad target placement, schedule, and budget. Monitor click-through rates and impressions for each active campaign.',
      hint: 'Use the Landing Hero slot for major campaigns — it has the highest visibility!',
      position: 'right',
      icon: 'Megaphone',
    },
  ],
};

export const TOUR_KEY = (role) => `nexify_tour_done_${role}`;
export const TOUR_DONE_VALUE = 'completed';
