/** * Admin Dashboard — Portal Shell * Full oversight: staging queue, global GMV, user management, asset overrides. * * Reference: PRD 6.2, SRS Persona A */ 

import React from 'react'; import { useAuth } from '../../context/AuthContext'; import { Navigate } from 'react-router-dom'; import { Wallet, Lock, ClipboardList, Users, FileBarChart, TrendingUp, Palette, Image, FolderOpen, LogOut } from 'lucide-react'; 

const stats = [ { label: 'Total GMV', value: 'GH₵ 0.00', icon: Wallet, color: 'text-emerald-400' }, { label: 'Platform Fees', value: 'GH₵ 0.00', icon: Lock, color: 'text-[#7C3AED]' }, { label: 'Pending Reviews', value: '0', icon: ClipboardList, color: 'text-amber-400' }, { label: 'Active Users', value: '0', icon: Users, color: 'text-white' }, ]; 

const sections = [ { title: 'Staging Queue', badge: 'LIVE', badgeColor: 'bg-amber-500/20 text-amber-400', icon: ClipboardList, desc: 'Course submissions awaiting admin review.', note: 'Connect to the API to load live data.' }, { title: 'Global Financial Analytics', badge: 'OVERVIEW', badgeColor: 'bg-[#7C3AED]/20 text-[#7C3AED]', icon: TrendingUp, desc: 'Platform-wide revenue, margins, and user metrics.', note: 'Available via /api/v1/admin/metrics' }, { title: 'User Management Grid', badge: 'ALL ROLES', badgeColor: 'bg-white/10 text-white/60', icon: Users, desc: 'Manage users, roles, and creator trust tiers.', note: 'Available via /api/v1/admin/users' }, { title: 'System Branding & Asset Manager', badge: 'UPLOADS', badgeColor: 'bg-[#7C3AED]/20 text-[#7C3AED]', icon: Palette, desc: 'Upload and manage platform branding assets.', note: 'Available via /api/v1/admin/assets' }, ]; 

const assets = [ { key: 'LOGO_MAIN', label: 'Main Logo', file: '/assets/branding/logo-main.svg' }, { key: 'LOGO_MAIN_LIGHT', label: 'Light Logo', file: '/assets/branding/logo-main-light.svg' }, { key: 'LOGO_NEXA', label: 'Nexa Logo', file: '/assets/branding/logo-nexa.svg' }, { key: 'PLACEHOLDER_COURSE', label: 'Course Placeholder', file: '/assets/branding/placeholder-course.jpg' }, { key: 'PLACEHOLDER_AVATAR', label: 'Avatar Placeholder', file: '/assets/branding/placeholder-avatar.png' }, { key: 'PAYMENT_BADGES', label: 'Payment Badges', file: '/assets/branding/icons/' }, ]; 

function AssetCard({ asset }) { const isSvg = asset.file.endsWith('.svg'); const isImage = asset.file.endsWith('.jpg') || asset.file.endsWith('.png'); 

return ( <div className="border border-white/10 rounded-xl p-4 bg-[#0F172A]"> <p className="text-xs font-medium text-white/40 uppercase tracking-wider mb-1">{asset.key}</p> <p className="text-sm font-medium text-white mb-2">{asset.label}</p> <div className="bg-white/5 rounded-md h-20 flex items-center justify-center border border-white/10"> {isSvg ? ( <svg className="w-8 h-8 text-white/30" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" /></svg> ) : isImage ? ( <Image className="w-8 h-8 text-white/30" /> ) : ( <FolderOpen className="w-8 h-8 text-white/30" /> )} </div> <button className="mt-2 w-full text-xs bg-[#7C3AED] text-black py-1.5 rounded-xl hover:bg-[#8b5cf6] active:scale-[0.97] transition-transform duration-120 cubic-bezier(0.23,1,0.32,1) font-medium"> Upload Override </button> </div> ); } 

export default function AdminDashboard() { const { user, logout } = useAuth(); 

return ( <div className="max-w-6xl"> {/* Page header */} <div className="mb-8"> <div className="flex items-center gap-3 mb-2"> <div className="w-8 h-8 bg-[#7C3AED] rounded-lg flex items-center justify-center"> <span className="text-black font-bold text-sm">N</span> </div> <h1 className="text-2xl font-bold text-white">Admin Dashboard</h1> </div> <p className="text-white/40 text-sm">Platform-wide oversight & management</p> </div> 

{/* Quick stats */} <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8"> {stats.map(stat => ( <div key={stat.label} className="bg-[#1E1B4B] border border-white/10 rounded-xl p-4"> <div className="flex items-center gap-2 mb-2"> <stat.icon className={`w-4 h-4 ${stat.color}`} /> <span className="text-xs font-medium text-white/40 uppercase tracking-wider">{stat.label}</span> </div> <p className={`text-xl font-bold ${stat.color}`}>{stat.value}</p> </div> ))} </div> 

{/* Sections */} {sections.map(section => ( <section key={section.title} className="bg-[#1E1B4B] border border-white/10 rounded-xl p-6 mb-6"> <h2 className="text-lg font-bold text-white mb-4 flex items-center gap-2"> <section.icon className="w-4 h-4 text-white/60" /> {section.title} <span className={`text-xs ${section.badgeColor} px-2 py-0.5 rounded-full`}>{section.badge}</span> </h2> <div className="text-center py-8 text-white/40"> <p className="text-sm">{section.desc}</p> <p className="text-xs text-white/20 mt-1">{section.note}</p> </div> </section> ))} 

{/* Assets */} <section className="bg-[#1E1B4B] border border-white/10 rounded-xl p-6"> <h2 className="text-lg font-bold text-white mb-4 flex items-center gap-2"> <Palette className="w-4 h-4 text-white/60" /> System Branding & Asset Manager <span className="text-xs bg-[#7C3AED]/20 text-[#7C3AED] px-2 py-0.5 rounded-full">UPLOADS</span> </h2> <div className="grid grid-cols-2 md:grid-cols-3 gap-4"> {assets.map(asset => ( <AssetCard key={asset.key} asset={asset} /> ))} </div> </section> 

{/* Footer bar */} <div className="mt-8 pt-4 border-t border-white/5 flex items-center justify-between"> <div> <p className="text-sm font-medium text-white">{user?.fullName}</p> <p className="text-xs text-white/40">{user?.email}</p> <span className="inline-block mt-1 px-2 py-0.5 bg-[#7C3AED] text-black text-xs font-medium rounded-full"> {user?.role} </span> </div> <button onClick={logout} className="text-sm text-white/40 hover:text-white transition-colors active:scale-[0.97] transition-transform duration-120 cubic-bezier(0.23,1,0.32,1)"> Sign Out </button> </div> </div> ); }